
<center>
    <img src="https://user-images.githubusercontent.com/67586773/105040771-43887300-5a88-11eb-9f01-bee100b9ef22.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


#### 
* Element-wise addition of 2 numpy arrays. Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?


In [31]:
# Sample Solution
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b # Element-wise addition
print(c)

[5 7 9]


#### --------------------------------------------------------------------------------------------------------------------------------
* Create a 3x3 identity matrix.

In [32]:
# Sample Solution
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### --------------------------------------------------------------------------------------------------------------------------------
* Create a null vector of size 10 but the fifth value which is 1

In [33]:
# Sample Solution
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### --------------------------------------------------------------------------------------------------------------------------------
* Compute the mean, median, standard deviation of a numpy array along the second axis.

In [34]:
# Sample Solution
import numpy as np
x = np.array([[14, 17, 12, 33, 44], 
              [15, 6, 27, 8, 19], 
              [23, 2, 54, 1, 4]])
print("Mean: ", np.mean(x, axis=1))
print("Median: ", np.median(x, axis=1))
print("Standard Deviation: ", np.std(x, axis=1))

Mean:  [24.  15.  16.8]
Median:  [17. 15.  4.]
Standard Deviation:  [12.44186481  7.61577311 20.27214838]


#### --------------------------------------------------------------------------------------------------------------------------------
* Reverse a vector (first element becomes last).

* Explanation: This exercise is about reversing the order of the elements in a numpy array. To do this, we can use slicing with a negative step size of -1. This means that we start from the end of the array and move backwards by one element at a time. The result is a new array that has the same elements as the original array but in reverse order.



In [35]:
# Sample Solution
import numpy as np
x = np.arange(10) # Create a numpy array of 10 elements from 0 to 9
x = x[::-1] # Reverse the array by using a negative step size of -1
print(x) # Print the reversed array


[9 8 7 6 5 4 3 2 1 0]


#### --------------------------------------------------------------------------------------------------------------------------------
* Create a 8x8 matrix and fill it with a checkerboard pattern.

* Explanation: This exercise is about creating a matrix that has a checkerboard pattern of zeros and ones. To do this, we can use slicing with different start, stop and step values to select different parts of the matrix and assign them to either zero or one. For example, Z[1::2,::2] means that we select every other row starting from row 1 (index 1) and every other column starting from column 0 (index 0). We assign these elements to one to create the checkerboard pattern. We do the same for Z[::2,1::2] but with different start values for rows and columns.



In [36]:
# Sample Solution
import numpy as np
Z = np.zeros((8,8),dtype=int) # Create a 8x8 matrix of zeros with integer data type
Z[1::2,::2] = 1 # Assign 1 to every other element in odd rows starting from row 1
Z[::2,1::2] = 1 # Assign 1 to every other element in even rows starting from column 1
print(Z) # Print the matrix


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### --------------------------------------------------------------------------------------------------------------------------------
* Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

* Explanation: This exercise is about creating a matrix that has values 1,2,3,4 just below the main diagonal. To do this, we can use the np.diag function that creates a diagonal matrix from a given array. We can also specify the position of the diagonal with the k parameter. If k is zero, it means the main diagonal. If k is negative, it means below the main diagonal. If k is positive, it means above the main diagonal. In this case, we want k to be -1 to create the matrix just below the main diagonal. We also use np.arange(4) to create an array of four elements from 0 to 3 and add one to each element to get the values 1,2,3,4.


In [37]:
# Sample Solution
import numpy as np
Z = np.diag(1+np.arange(4),k=-1) # Create a diagonal matrix with values 1,2,3,4 just below the main diagonal (k=-1)
print(Z) # Print the matrix

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### --------------------------------------------------------------------------------------------------------------------------------
* Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [38]:
# Sample Solution
import numpy as np
x = np.linspace(5, 50, 10)
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


#### --------------------------------------------------------------------------------------------------------------------------------
* Write a NumPy program to create a random vector of size 10 and sort it.

In [39]:
# Sample Solution
import numpy as np
x = np.random.random(10)
x.sort()
print(x)


[0.02831269 0.08234539 0.17342988 0.19574336 0.34445316 0.67329123
 0.70662743 0.83942799 0.85291826 0.94124853]


#### --------------------------------------------------------------------------------------------------------------------------------
* Create an array and print its various ranges.


In [40]:
# Sample Solution
import numpy as np
x = np.array([[14, 17, 12, 33, 44], 
              [15, 6, 27, 8, 19], 
              [23, 2, 54, 1, 4]])

print(x[0:2,0:3])

[[14 17 12]
 [15  6 27]]
